spring.application.name=api-pesca-merida
# Habilita la consola de H2 para que entres desde el navegador
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:pescayucatandb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
app.seeder.enabled=false
# Muestra en la consola de IntelliJ las consultas SQL que Spring hace por ti
spring.jpa.show-sql=true
#  JPA MUY IMPORTANTE
# NUNCA usar create o create-drop cuando Flyway está activo.
# validate verifica que tus entidades coincidan con el esquema real.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true

