spring.application.name=api-pesca-merida

# H2 Console (desarrollo)
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:pescayucatandb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true

# URLs de Google Sheets (Formato Exportacion Directa a CSV)
ingestion.sheets.especies-url=https://docs.google.com/spreadsheets/d/1lrzoWe_YgU5S0UULppk8q33CSd26Gu82TiWxerKpqWQ/export?format=csv&gid=382368478
ingestion.sheets.vedas-url=https://docs.google.com/spreadsheets/d/1lrzoWe_YgU5S0UULppk8q33CSd26Gu82TiWxerKpqWQ/export?format=csv&gid=0

# Cron: Lunes a las 3 AM
ingestion.cron=0 0 3 * * MON

# Habilitar ingesta
ingestion.enabled=true

#CORS origins
cors.allowed.origins="https://pesca-merida.com","http://localhost:3000","http://localhost:5173"
