spring.application.name=api-pesca-merida
# Habilita la consola de H2 para que entres desde el navegador
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:pescayucatandb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Muestra en la consola de IntelliJ las consultas SQL que Spring hace por ti
spring.jpa.show-sql=true